### ISSUE TITLE
Initial Structure Setup: Basic Discord Bot 

### ISSUE THREAD

**Issue by firasrg** [open-dev-union/odu-website#10]
With the initial [modeling and requirements established](https://open-dev-union.github.io/odu-website/bot/), it's time to initiate the bot's development. The bot should be able to handle [the initially defined use cases](https://open-dev-union.github.io/odu-website/bot/modeling#use-cases).

**Tasks**:
- [ ] Initialize a basic bot app.
- [ ] Implement at least one initial feature:
   - [ ] Auto-welcome
   - [ ] Mention server rules
   - [ ] Help command
   - [ ] Auto welcome question

**Requirements**:
- Must be written in TypeScript.
- Should make use of the Discord.js library.
- Code should be well-organized, maintainable, and documented.
