### ISSUE TITLE
Automatic Publishing Between Code and GitHub Pages Repos

### ISSUE THREAD

**Issue by firasrg** [open-dev-union/odu-website#8]
We currently maintain two separate repositories:
1. `odu-website` (this) - where we host and develop our website's codebase.
2. `open-dev-union.github.io` - designated for [GitHub Pages](https://pages.github.com/) deployment.

We need to set up a mechanism to automate the publishing process between these two repositories. Each time we push an update to branch **main** in this repo, the contents of the `/build` directory should automatically be pushed to the `open-dev-union.github.io` repo's main branch!

#### **Goals**
1. Ensure the content on GitHub Pages is always in sync with our latest development changes.
2. Reduce manual efforts and potential human errors.

#### **Tasks**
- [x] Investigate possible solutions/tools for this automation.
- [x] Use [GitHub Action](https://github.com/features/actions) to automate the publishing process.
- [x] Test the automated process with minor updates.
- [x] Document the workflow.

**Comment by firasrg** [comment]
FYI, it seems that it's possible to use only one repository (this one) to do code and GitHub pages purposes.
